### ISSUE TITLE
go client

### ISSUE THREAD

**Issue by gedw99** [jirenius/resgate#52]
Hey @jirenius Congrats on getting onto the NATS blog :)
The article is well written.

I am wondering what happened to the go-client ? Cant find the repo for it.

**Comment by gedw99** [comment]
ah founf it: https://github.com/jirenius/go-res

Is this going to be supported going forward ? I worked out a way to use this from Dart without having to use any nodejs etc.

**Comment by jirenius** [comment]
Hi @gedw99! Thanks about the blog. And nice hearing you from again! :)

Regarding package `github.com/jirenius/go-res`, yes, it will be officially supported by myself.  
However, as the [README](https://github.com/jirenius/go-res/blob/master/README.md) says under *Contribution* (?), I may still make breaking changes to the `go-res` package API.  
I have actually been working a bit on it the last two days, trying to make it easy to use, yet flexible enough that you can do whatever you want to within the boundaries of the RES protocol specifications.

You used the `go-res` code in Dart? Dart can load Go code?! Or you mean, you used Dart as the language to make a service?  
Anyhow, I would love to see it! :D

I haven't looked fully into nkeys, but understand that you can restrict what subjects (aka. topics) a NATS client (that is, Resgate, or any of the microservices) may subscribe or publish to. While I do like the feature, I don't see that it would add much to Resgate's already existing security. Well, except for perhaps restricting Resgate to only be allowed to subscribe to the range of topics specified by the RES protocol - just in case a hacker found a way to make a Resgate publish arbitrary requests onto NATS.

But since a hacker only has access to Resgate's WebSocket, never the NATS server, they are bound by the strict rules of the RES protocol. I believe the nkeys feature in NATS is primarily to allow non-trusted NATS clients to connect directly to a NATS server. Resgate can be considered trusted.

What sort of attack vector against a Resgate API do you see that would get more secure with nkeys?

To allow using Resgate and NATS on different servers, I have planned to add support to Resgate to make encrypted connections to NATS, and utilizing user/password or token based authentication, supported by [NATS Server](https://github.com/nats-io/gnatsd).

https://godoc.org/github.com/nats-io/nats#UserInfo

As I said, glad to hear from you again, and to try answering your questions :)

**Comment by gedw99** [comment]
You can run golang inside of flutter. So that mean I don't really need a
dart resgate client.
So you can build mobile and desktop apps with it.

There is a web browser version of flutter coming and golang can run their
too. But that's not being admitted to by Google skia team.

Anyways I saw the tidy up in the resgate  code is much cleaner and will try
again

**Comment by jirenius** [comment]
Closing topic
